config/routes.rb
Rails.application.routes.draw do
  resources :devices, :except => [:destroy] do
    member do
      get :dashboard
      post :on
      post :off
    end
    resources :locations, :except => [:new, :edit, :update, :destroy]
  end
end

app/models/device.rb
class Device < ActiveRecord::Base

	has_many :locations

	def particle_endpoint
		"https://api.particle.io/v1/devices/#{particle_id}/"
	end

	def post_particle_function!(command)
		RestClient.post(
			particle_endpoint + command,
			:access_token => access_token
			)
	end

	def get_particle_variable(command)
		resp = RestClient.get(
			particle_endpoint + command,
				{
					:params => {
						:access_token => access_token
					}
				}
			)
		JSON.parse(resp)["result"]
	end


	def turn_on!
		post_particle_function!("turnon")
	end

	def turn_off!
		post_particle_function!("turnoff")
	end

	def on?
		get_particle_variable("O") == 1
	end

	def power_level
		get_particle_variable("P")
	end

	def coords
		@coords ||= get_particle_variable("L")
	end

	def location
		if coords.blank?
			nil
		else
			@location ||= Geocoder.search(coords).first.formatted_address
		end
	end

	def coords_time
		if coords.blank?
			nil
		else
			Time.at(get_particle_variable("T")).to_datetime
		end
	end

	def nearby_locations
		current_location = locations.last
		if locations.last
			locations.order(:id => :desc).limit(5).near(current_location, 0.5, :units => :km)
		else
			[]
		end
	end


end

app/models/location.rb
class Location < ActiveRecord::Base

	belongs_to :device

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def google_map_url
		"http://www.google.com/maps/place/#{address}/@#{latitude},#{longitude},16z"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, :except => [:index, :new, :create]

  def index
    @devices = Device.all
  end

  def show
    @hash = Gmaps4rails.build_markers(@device.nearby_locations) do |loc, marker|
      marker.lat loc.latitude
      marker.lng loc.longitude
    end
  end

  def new
    @device = Device.new
  end

  def edit
  end

  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to device_path(@device.particle_id), flash: { info: 'Device was successfully created.' }}
        format.json { render :show, status: :created, location: device_path(@device.particle_id) }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to device_path(@device.particle_id), flash: { info: 'Device was successfully updated.' }}
        format.json { render :show, status: :ok, location: device_path(@device.particle_id) }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def on
    @device.turn_on!
    redirect_to device_dashboard_path(@device), flash: { success: 'Device was turned on.' }
  end

  def off
    @device.turn_off!
    redirect_to device_dashboard_path(@device), flash: { success: 'Device was turned on.' }
  end


  def dashboard
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find_by_particle_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:timestamps, :name, :particle_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  before_action :set_device
  protect_from_forgery :except => :create
  
  def create
    @location = @device.locations.build(location_params)

    respond_to do |format|
      if @location.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find_by_particle_id(params[:device_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude)
    end
end

app/controllers/untitled.rb
class PingsController < ApplicationController
  before_action :set_device, only: [:create]

  def create
    respond_to do |format|
      format.json { render json: {ping: "success"}, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for @device, :url => device_path(@device.particle_id), :html => { :class => "form-horizontal device" } do |f| %>

  <% if @device.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :particle_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :particle_id, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                devices_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/devices/dashboard.html.erb
<% model_class = Device %>
<div class="row page-header">
	<h1><%=t '.title', :default => "#{model_class} Dashboard" %></h1>
</div>

<div class="row">
	<dl>
		<dt><strong>Name:</strong></dt>
		<dd><%= @device.name %></dd>
		<dt><strong>Power Remaining:</strong></dt>
		<dd><%= "#{@device.power_level}%"%></dd>
</div>

<div class="row">
	<% if @device.on? %>
		<%= link_to 'Turn Off', off_device_path(@device), :method => :post, :class => 'btn btn-warning' %>
	<% else %>
		<%= link_to 'Turn On', on_device_path(@device), :method => :post, :class => 'btn btn-default' %>
	<% end %>
	<%= link_to t('.back', :default => t("helpers.links.back")),
								device_path(@device.particle_id), :class => 'btn btn-default', :method => :get  %>
</div>

app/views/devices/edit.html.erb
<% model_class = Device %>
<div class="page-header">
	<h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Particle Id</th>
      <th>Created On</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.name, device_path(device.particle_id) %></td>
        <td><%= device.particle_id %></td>
        <td><%= device.created_at.strftime("%m-%d-%Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device.particle_id), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      device_path(device.particle_id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/show.html.erb
<div class="row page-header">
	<h1><%=t '.title', :default => @device.name %></h1>
</div>

<div class="row">
	<% if @device.on? %>
		<%= link_to 'Turn Off', off_device_path(@device), :method => :post, :class => 'btn btn-warning' %>
	<% else %>
		<%= link_to 'Turn On', on_device_path(@device), :method => :post, :class => 'btn btn-default' %>
	<% end %>
</div>

<div class="row">
	<dl>
		<dt><strong>Name:</strong></dt>
		<dd><%= @device.name %></dd>
		<dt><strong>Particle Id:</strong></dt>
		<dd><%= @device.particle_id %></dd>
		<dt><strong>Power Remaining:</strong></dt>
		<dd><%= "#{@device.power_level}%"%></dd>
		<dt><strong>Locations:</strong></dt>
		<%= render(@device.nearby_locations) || "There are no locations available." %>
	</dl>
</div>

<div style='width: 800px;'>
	<div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div id="markers" data-markers=<%=raw @hash.to_json %> ></div>

<div class="row">
	<%= link_to t('.back', :default => t("helpers.links.back")),
								devices_path, :class => 'btn btn-default', :method => :get  %>
	<%= link_to t('.edit', :default => t("helpers.links.edit")),
								edit_device_path(@device), :class => 'btn btn-default', :method => :get %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GuardianStoneApp</title>
	<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
	<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body role="document">
	<div class="container theme-showcase" role="main">
		<%= render :partial => "shared/flash" %>
		<%= yield %>
	</div>

</body>
</html>

app/views/locations/_location.html.erb
<dd><%=local_time(location.created_at)%> - <%=link_to(location.address, location.google_map_url)%></dd>

app/views/locations/show.html.erb
<div style='width: 800px;'>
	<div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
	<div class="row">
		<%= content_tag :div, msg, :class => "alert-#{name}", :role => "alert" %>
	</div>
	<% end %>
<% end %>